### PR TITLE
add a new parameter: syncRobotBridgeTimeStampUS

### PR DESCRIPTION
**Pull request by eisoku9618**

### CODE REVIEW

**Comment by eisoku9618** [comment]
seems not necessary.

**Comment by rdiankov** [comment]
Why not?

**Comment by eisoku9618** [comment]
cc @felixvd @hemangandhi

**Comment by eisoku9618** [comment]
re-open just in case.

**Comment by eisoku9618** [comment]
~~`Reopen pull requset` button seems not working with my account permission level.~~ :cry:

**Comment by eisoku9618** [comment]
oh it was because I deleted the branch already. Trying `Reopen and comment` button again.

**Comment by felixvd** [comment]
@eisoku9618 I mentioned in person that the file that this MR changes is an auto-generated type annotation that shouldn't be updated by hand, but it's OK to merge this in the meantime.

**Comment by felixvd** [comment]
Pushed a clarification, LGTM

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
